version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8084:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - FAIL_MODE=false

volumes:
  jenkins_home: