apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app-rollout
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: health-check-template
        - setWeight: 50
        - pause: { duration: 60s }
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: demo-app:latest
          ports:
            - containerPort: 8089

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-check-template
spec:
  metrics:
    - name: http-health-check
      successCondition: "result == '200'"
      provider:
        web:
          url: http://localhost:8089/health
