name: Self-Healing Java App on Docker

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Step 3: Build Docker image for the application
      - name: Build Docker image
        run: |
          docker build -t my-java-app .

      # Step 4: Run Docker container for the application
      - name: Run Docker container
        run: |
          docker run -d --name my-java-app-container -p 8090:8090 my-java-app

      # Step 5: Monitor the health of the application and restart the container if necessary
      - name: Monitor and heal application
        run: |
          # Check the health of the container by sending a simple request to the app
          while true; do
            echo "Checking if the app is alive..."
          
            # Send a request to check if the application is healthy
            if ! curl --silent --fail http://localhost:8090/health; then
              echo "App is down. Restarting the container..."
              docker restart my-java-app-container
            else
              echo "App is healthy."
            fi
          
            # Sleep for a period (e.g., 30 seconds) before checking again
            sleep 30
          done
