name: Build and Deploy Self-Healing Java App on Docker

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Docker image
        run: |
          docker build -t demo-app .

      - name: Run Docker container
        run: |
          docker run --rm -d --name demo-app -p 8090:8090 demo-app

      - name: Monitor and heal application
        run: |
          # Check the health of the container by sending a simple request to the app
          while true; do
            echo "Checking if the app is alive..."
          
            # Send a request to check if the application is healthy
            if ! curl --silent --fail http://localhost:8090/health; then
              echo "App is down. Capturing logs and restarting the container..."
              
              # Capture logs for diagnosis
              docker logs demo-app > demo-app.log
              
              # Restart the container
              docker restart demo-app
              
              # Check if the container restarted successfully
              if [ "`docker inspect -f {{.State.Running}} demo-app`" != "true" ]; then
                echo "Failed to restart the container. Exiting..."
                exit 1
              fi
            else
              echo "App is healthy."
            fi
          
            # Sleep for a period (e.g., 30 seconds) before checking again
            sleep 30
          done
