name: Build and Deploy Self-Healing Java App on Docker

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build the project
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t demo-app .

      - name: Run Docker container
        run: docker run -d --name demo-app-container2 -p 8089:8089 demo-app

      - name: Check if the app is running
        run: |
          sleep 10
          curl -f http://localhost:8089/health || (echo "App is not running" && exit 1)
